name: travel_guide_app
description: "Pathio - Your Path, Perfected. A travel guide app for discovering places and planning trips."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  go_router: ^16.2.4
  http: ^1.1.0
  shared_preferences: ^2.5.3
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  firebase_storage: ^12.3.4
  lottie: ^3.1.2
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/splash_screen.json
    - assets/logo/
    - screenshots/


flutter_launcher_icons:
  android: true
  ios: false # Set to false if you're only targeting Android

  # Path for the standard icon (for older Android/iOS versions)
  # You can use the same foreground image here.
  image_path: "assets/logo/abc.png"

  # Adaptive Icon specific settings for modern Android
  adaptive_icon_background: "#F5F5F5" # Your desired background color
  adaptive_icon_foreground: "assets/logo/abc.png" # Path to your foreground image

